{
 "title": "JMeter Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "data_source", "query": "influxdb" },
   { "name": "measurement", "query": { "query": "SHOW MEASUREMENTS" } },
   {
    "name": "generator",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"generator\""
    }
   },
   {
    "name": "profile_name",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"profile_name\""
    }
   },
   {
    "name": "system_name",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"system_name\""
    }
   },
   { "name": "send_interval", "query": "5,10,15,30" }
  ]
 },
 "panels": [
  {
   "title": "Active Threads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Threads" } },
   "targets": [
    {
     "alias": "Threads",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "maxAT" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "generator::tag", "operator": "=~", "value": "/^$generator$/" },
      { "condition": "AND", "key": "profile_name::tag", "operator": "=~", "value": "/^$profile_name$/" },
      { "condition": "AND", "key": "system_name::tag", "operator": "=~", "value": "/^$system_name$/" }
     ]
    }
   ]
  },
  {
   "title": "UR RPS (Total)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "alias": "RPS OK",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $send_interval" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "transaction::tag", "operator": "=~", "value": "/^ur.*/" },
      { "condition": "AND", "key": "statut::tag", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "generator::tag", "operator": "=~", "value": "/^$generator$/" },
      { "condition": "AND", "key": "profile_name::tag", "operator": "=~", "value": "/^$profile_name$/" },
      { "condition": "AND", "key": "system_name::tag", "operator": "=~", "value": "/^$system_name$/" }
     ]
    },
    {
     "alias": "RPS KO",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $send_interval" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "transaction::tag", "operator": "=~", "value": "/^ur.*/" },
      { "condition": "AND", "key": "statut::tag", "operator": "=", "value": "ko" }
     ]
    },
    {
     "alias": "RPS Total",
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / $send_interval" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "transaction::tag", "operator": "=~", "value": "/^ur.*/" },
      { "condition": "AND", "key": "statut::tag", "operator": "=", "value": "all" }
     ]
    }
   ]
  },
  {
   "title": "UR SUCCESSFUL %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"OK\") / sum(\"ALL\")\nFROM (\n    SELECT sum(\"count\") as \"OK\"\n    FROM \"jmeter\"\n    WHERE (\"transaction\"::tag =~ /^ur.*/ AND \"statut\"::tag = 'ok' AND \"generator\"::tag =~ /^$generator$/ AND \"profile_name\"::tag =~ /^$profile_name$/ AND \"system_name\"::tag =~ /^$system_name$/) AND $timeFilter\n    GROUP BY time(30s) fill(null)\n),\n(\n    SELECT sum(\"count\") as \"ALL\"\n    FROM \"jmeter\"\n    WHERE (\"transaction\"::tag =~ /^ur.*/ AND \"statut\"::tag = 'ok' OR \"statut\"::tag = 'ko' AND \"generator\"::tag =~ /^$generator$/ AND \"profile_name\"::tag =~ /^$profile_name$/ AND \"system_name\"::tag =~ /^$system_name$/) AND $timeFilter\n    GROUP BY time(30s) fill(null)\n)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "statut::tag", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "UR ERROR %",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "30s" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"KO\") / sum(\"ALL\")\nFROM (\n    SELECT sum(\"count\") as \"KO\"\n    FROM \"jmeter\"\n    WHERE (\"transaction\"::tag =~ /^ur.*/ AND \"statut\"::tag = 'ko' AND \"generator\"::tag =~ /^$generator$/ AND \"profile_name\"::tag =~ /^$profile_name$/ AND \"system_name\"::tag =~ /^$system_name$/) AND $timeFilter\n    GROUP BY time(30s) fill(null)\n),\n(\n    SELECT sum(\"count\") as \"ALL\"\n    FROM \"jmeter\"\n    WHERE (\"transaction\"::tag =~ /^ur.*/ AND \"statut\"::tag = 'ok' OR \"statut\"::tag = 'ko' AND \"generator\"::tag =~ /^$generator$/ AND \"profile_name\"::tag =~ /^$profile_name$/ AND \"system_name\"::tag =~ /^$system_name$/) AND $timeFilter\n    GROUP BY time(30s) fill(null)\n)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "statut::tag", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "Summery",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors Per Transaction",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "transaction::tag" ], "type": "tag" },
        { "params": [ "statut::tag" ], "type": "tag" }
       ],
       "measurement": "/^$measurement$/",
       "query": "SELECT sum(\"count\") FROM /^$measurement$/ WHERE (\"transaction\"::tag =~ /^ur.*/ AND \"generator\"::tag =~ /^$generator$/ AND \"profile_name\"::tag =~ /^$profile_name$/ AND \"system_name\"::tag =~ /^$system_name$/) AND $timeFilter GROUP BY \"transaction\"::tag, \"statut\"::tag",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "transaction::tag", "operator": "=~", "value": "/^ur.*/" },
        { "condition": "AND", "key": "generator::tag", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "profile_name::tag", "operator": "=~", "value": "/^$profile_name$/" },
        { "condition": "AND", "key": "system_name::tag", "operator": "=~", "value": "/^$system_name$/" }
       ]
      }
     ]
    },
    {
     "title": "Error Info",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "responseCode::tag" ], "type": "tag" },
        { "params": [ "responseMessage::tag" ], "type": "tag" },
        { "params": [ "transaction::tag" ], "type": "tag" }
       ],
       "measurement": "/^$measurement$/",
       "query": "SELECT sum(\"count\") FROM /^$measurement$/ WHERE (\"statut\"::tag = 'ko' OR \"statut\"::tag = 'all') AND $timeFilter GROUP BY \"transaction\", \"statut\"",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "responseCode::tag", "operator": "!~", "value": "/^$/" },
        { "condition": "AND", "key": "generator::tag", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "profile_name::tag", "operator": "=~", "value": "/^$profile_name$/" },
        { "condition": "AND", "key": "system_name::tag", "operator": "=~", "value": "/^$system_name$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "UC RPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "UC RPS",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "transaction::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / $send_interval" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "transaction::tag", "operator": "=~", "value": "/^uc.*/" },
        { "condition": "AND", "key": "statut::tag", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "generator::tag", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "profile_name::tag", "operator": "=~", "value": "/^$profile_name$/" },
        { "condition": "AND", "key": "system_name::tag", "operator": "=~", "value": "/^$system_name$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "UC Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "UC 99%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "transaction::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "pct99.0" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "transaction::tag", "operator": "=~", "value": "/^uc.*/" },
        { "condition": "AND", "key": "generator::tag", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "profile_name::tag", "operator": "=~", "value": "/^$profile_name$/" },
        { "condition": "AND", "key": "system_name::tag", "operator": "=~", "value": "/^$system_name$/" }
       ]
      }
     ]
    },
    {
     "title": "UC 95%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "transaction::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "transaction::tag", "operator": "=~", "value": "/^uc.*/" },
        { "condition": "AND", "key": "generator::tag", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "profile_name::tag", "operator": "=~", "value": "/^$profile_name$/" },
        { "condition": "AND", "key": "system_name::tag", "operator": "=~", "value": "/^$system_name$/" }
       ]
      }
     ]
    },
    {
     "title": "UC 90%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "transaction::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "pct90.0" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "transaction::tag", "operator": "=~", "value": "/^uc.*/" },
        { "condition": "AND", "key": "generator::tag", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "profile_name::tag", "operator": "=~", "value": "/^$profile_name$/" },
        { "condition": "AND", "key": "system_name::tag", "operator": "=~", "value": "/^$system_name$/" }
       ]
      }
     ]
    },
    {
     "title": "UC 50%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "transaction::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "pct50.0" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "transaction::tag", "operator": "=~", "value": "/^uc.*/" },
        { "condition": "AND", "key": "generator::tag", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "profile_name::tag", "operator": "=~", "value": "/^$profile_name$/" },
        { "condition": "AND", "key": "system_name::tag", "operator": "=~", "value": "/^$system_name$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "UR RPS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "UR RPS (OK)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 735 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "transaction::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / $send_interval" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "transaction::tag", "operator": "=~", "value": "/^ur.*/" },
        { "condition": "AND", "key": "statut::tag", "operator": "=", "value": "ok" },
        { "condition": "AND", "key": "generator::tag", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "profile_name::tag", "operator": "=~", "value": "/^$profile_name$/" },
        { "condition": "AND", "key": "system_name::tag", "operator": "=~", "value": "/^$system_name$/" }
       ]
      }
     ]
    },
    {
     "title": "UR RPS (ERROR)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 735 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "transaction::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "jmeter",
       "select": [
        [
         { "params": [ "count" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         },
         { "params": [ " / $send_interval" ], "type": "math" }
        ]
       ],
       "tags": [
        { "key": "transaction::tag", "operator": "=~", "value": "/^ur.*/" },
        { "condition": "AND", "key": "statut::tag", "operator": "=", "value": "ko" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "UR Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "UR 99%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 234 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "transaction::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "pct99.0" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "transaction::tag", "operator": "=~", "value": "/^ur.*/" },
        { "condition": "AND", "key": "generator::tag", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "profile_name::tag", "operator": "=~", "value": "/^$profile_name$/" },
        { "condition": "AND", "key": "system_name::tag", "operator": "=~", "value": "/^$system_name$/" }
       ]
      }
     ]
    },
    {
     "title": "UR 95%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 234 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "transaction::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "pct95.0" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "transaction::tag", "operator": "=~", "value": "/^ur.*/" },
        { "condition": "AND", "key": "generator::tag", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "profile_name::tag", "operator": "=~", "value": "/^$profile_name$/" },
        { "condition": "AND", "key": "system_name::tag", "operator": "=~", "value": "/^$system_name$/" }
       ]
      }
     ]
    },
    {
     "title": "UR 90%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 242 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "transaction::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "pct90.0" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "transaction::tag", "operator": "=~", "value": "/^ur.*/" },
        { "condition": "AND", "key": "generator::tag", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "profile_name::tag", "operator": "=~", "value": "/^$profile_name$/" },
        { "condition": "AND", "key": "system_name::tag", "operator": "=~", "value": "/^$system_name$/" }
       ]
      }
     ]
    },
    {
     "title": "UR 50%",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 242 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "$tag_transaction",
       "groupBy": [
        { "params": [ "30s" ], "type": "time" },
        { "params": [ "transaction::tag" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "/^$measurement$/",
       "select": [
        [
         { "params": [ "pct50.0" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "transaction::tag", "operator": "=~", "value": "/^ur.*/" },
        { "condition": "AND", "key": "generator::tag", "operator": "=~", "value": "/^$generator$/" },
        { "condition": "AND", "key": "profile_name::tag", "operator": "=~", "value": "/^$profile_name$/" },
        { "condition": "AND", "key": "system_name::tag", "operator": "=~", "value": "/^$system_name$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}